### ISSUE TITLE
 why？

### ISSUE THREAD

**Issue by jeje9527** [sourcelocation/deb-to-ipa-app#1]
![44EC6EC0-073B-4B90-93A0-ADF2924C1911](https://user-images.githubusercontent.com/48116066/195888923-733387f5-ce05-487a-8450-b78c2fa5c209.png)

**Comment by yisaings** [comment]
？![image](https://user-images.githubusercontent.com/55074029/195896696-a268a9f7-1306-4993-be13-5c1a7a022b18.png)

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/195919489-27df57c9-0423-46eb-8b20-53f09be304c7.png)

**Comment by sourcelocation** [comment]
Fixed in 0.2, can you please test?

**Comment by mihai91** [comment]
On iOS 15.1 Iphone XS, i could convert and install only the DrainCheck app however the app doesn't start obviously
